//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTURelayControl.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiText() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RTURelayControl.Resources.UiText", typeof(UiText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string AboutBoxCaption {
            get {
                return ResourceManager.GetString("AboutBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Программа позволяет управлять платами реле с китая и считывать их состояние через последовательный порт по протоколу Modbus RTU. Поддерживается одновременная работа нескольких устройств с разными адресами на одном COM интерфейсе. Поддерживаемые Modbus комманды описаны в руководстве..
        /// </summary>
        internal static string AboutBoxDescription {
            get {
                return ResourceManager.GetString("AboutBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для связи:.
        /// </summary>
        internal static string AboutBoxFeedBack {
            get {
                return ResourceManager.GetString("AboutBoxFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия.
        /// </summary>
        internal static string AboutBoxVersion {
            get {
                return ResourceManager.GetString("AboutBoxVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        internal static string ButtonAccept {
            get {
                return ResourceManager.GetString("ButtonAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        internal static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string ErrMessageBox {
            get {
                return ResourceManager.GetString("ErrMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        internal static string IsAdminRights {
            get {
                return ResourceManager.GetString("IsAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры порта.
        /// </summary>
        internal static string PortSettingsCaption {
            get {
                return ResourceManager.GetString("PortSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чет.
        /// </summary>
        internal static string PortSettingsCBoxParityEven {
            get {
                return ResourceManager.GetString("PortSettingsCBoxParityEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маркер.
        /// </summary>
        internal static string PortSettingsCBoxParityMark {
            get {
                return ResourceManager.GetString("PortSettingsCBoxParityMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string PortSettingsCBoxParityNone {
            get {
                return ResourceManager.GetString("PortSettingsCBoxParityNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нечет.
        /// </summary>
        internal static string PortSettingsCBoxParityOdd {
            get {
                return ResourceManager.GetString("PortSettingsCBoxParityOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пробел.
        /// </summary>
        internal static string PortSettingsCBoxParitySpace {
            get {
                return ResourceManager.GetString("PortSettingsCBoxParitySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бит в секунду:.
        /// </summary>
        internal static string PortSettingsLabelBaudRate {
            get {
                return ResourceManager.GetString("PortSettingsLabelBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер COM порта:.
        /// </summary>
        internal static string PortSettingsLabelCOMPort {
            get {
                return ResourceManager.GetString("PortSettingsLabelCOMPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бит данных:.
        /// </summary>
        internal static string PortSettingsLabelDataBit {
            get {
                return ResourceManager.GetString("PortSettingsLabelDataBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Четность:.
        /// </summary>
        internal static string PortSettingsLabelParity {
            get {
                return ResourceManager.GetString("PortSettingsLabelParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоповые биты:.
        /// </summary>
        internal static string PortSettingsLabelStopBit {
            get {
                return ResourceManager.GetString("PortSettingsLabelStopBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось изменить настройку автозагрузки приложения.
        /// </summary>
        internal static string SettingsAutoStartChngErr {
            get {
                return ResourceManager.GetString("SettingsAutoStartChngErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверные настройки.
        /// </summary>
        internal static string SettingsFormErrMessage {
            get {
                return ResourceManager.GetString("SettingsFormErrMessage", resourceCulture);
            }
        }
    }
}
